export type PoiGuideContent={shortIntro:string;description:string;whyVisit?:string;history?:string;whatToSee?:string;curiosities?:string;practicalTips?:string;sourceLabel:string;sourceUrl:string};
export type FoodSpecialty={name:string;description:string;icon:string};
export type CityGuideContent={subtitle:string;introduction:string;history:string;special:string;food:string;foodSpecialties?:FoodSpecialty[];tips:string;localTip?:string;sourceLabel:string;sourceUrl:string};
const regional='Visit Sicily — portale ufficiale della Regione Siciliana';
const simple=(subtitle:string,foodSpecialties:FoodSpecialty[],localTip:string,sourceUrl:string):CityGuideContent=>({subtitle,introduction:`${subtitle}. Una tappa da vivere con calma, intrecciando il programma del viaggio con la vita quotidiana del luogo.`,history:'Il paesaggio urbano e le tradizioni locali riflettono le molte stratificazioni culturali della Sicilia. Per approfondimenti storici e accessi è sempre preferibile consultare le fonti territoriali aggiornate.',special:'Qui il valore della visita nasce dal rapporto fra architettura, paesaggio e abitudini locali, non da un singolo monumento.',food:'Specialità territoriali da cercare senza attribuire a una sola città tradizioni diffuse in aree più ampie.',foodSpecialties,tips:localTip,localTip,sourceLabel:regional,sourceUrl});
export const cityGuideContent:Record<string,CityGuideContent>={
catania:{subtitle:'Sotto l’Etna, tra lava e barocco',introduction:'Catania è una città di contrasti: la pietra lavica scura incontra le facciate chiare del barocco, i mercati popolari convivono con palazzi e teatri monumentali, mentre l’Etna resta una presenza visiva e culturale costante.',history:'Il centro storico attuale racconta soprattutto la grande ricostruzione successiva al terremoto del 1693. Catania fu ricostruita sul sito della città precedente con un disegno urbano coerente e un linguaggio tardo-barocco che oggi partecipa al sito UNESCO delle città del Val di Noto.',special:'La sua identità nasce dall’unione fra architettura, vita di strada e paesaggio vulcanico. Piazza Duomo, via Crociferi, via Etnea e la Pescheria mostrano aspetti diversi ma complementari della città.',food:'Tre assaggi molto legati alla cultura cittadina.',foodSpecialties:[{icon:'🍝',name:'Pasta alla Norma',description:'Pasta con pomodoro, melanzane fritte, ricotta salata e basilico, ufficialmente indicata da Visit Sicily come originaria di Catania.'},{icon:'🍙',name:'Arancino',description:'A Catania è comune il nome maschile e la caratteristica forma appuntita; l’origine siciliana è condivisa e contesa, quindi non va trattata come esclusiva.'},{icon:'🍧',name:'Granita con brioche',description:'Una colazione o pausa molto diffusa nella Sicilia orientale, disponibile in gusti che cambiano con stagione e locale.'}],tips:'Il centro si comprende bene a piedi. Guarda il rapporto tra edifici chiari e basamenti in pietra lavica e lascia tempo anche alla vita quotidiana delle piazze.',localTip:'Abbina la Pescheria al Duomo al mattino e lascia Via Crociferi alle ore più tranquille, quando è più facile leggerne le prospettive.',sourceLabel:'Visit Sicily e Turismo Comune di Catania',sourceUrl:'https://www.visitsicily.info/en/ricetta/pasta-alla-norma-eng/'},
taormina:simple('Balconi sullo Ionio e vicoli da passeggio',[{icon:'🍧',name:'Granita',description:'Molto diffusa nella Sicilia orientale: una pausa naturale durante la passeggiata, senza attribuirle un’origine esclusivamente taorminese.'},{icon:'🐟',name:'Pesce locale',description:'Sulla costa ionica vale la pena privilegiare preparazioni semplici e pescato dichiarato dal locale.'}], 'Il corso è piacevole presto o verso sera; nelle ore centrali cerca anche le strade laterali, meno affollate.','https://www.visitsicily.info/wp-content/uploads/2026/04/Brochure_emozione_autentica_ITA_2026.pdf'),
ortigia:simple('L’isola storica di Siracusa',[{icon:'🐟',name:'Pesce e frutti di mare',description:'Il mercato di Ortigia mostra il legame della città con il mare; provenienza e disponibilità vanno chieste sul posto.'},{icon:'🌰',name:'Dolci di mandorla',description:'I prodotti alla mandorla sono molto diffusi nel sud-est siciliano e compaiono fra i profumi del mercato di Ortigia.'}], 'Attraversa il mercato al mattino, poi torna sul lungomare verso il tramonto: sono due volti complementari dell’isola.','https://www.visitsicily.info/en/localita/siracusa/'),
siracusa:simple('Teatri antichi e paesaggio mediterraneo',[{icon:'🌰',name:'Pasticceria di mandorla',description:'Una tradizione ampiamente diffusa nel Siracusano e nel Val di Noto.'},{icon:'🐟',name:'Cucina di mare',description:'Da provare privilegiando ingredienti stagionali e preparazioni legate al pescato locale.'}], 'Per la Neapolis evita le ore più calde; riserva la passeggiata di Ortigia alla luce del tardo pomeriggio.','https://www.visitsicily.info/en/localita/siracusa/'),
noto:simple('La città di pietra dorata',[{icon:'🍧',name:'Granita',description:'Visit Sicily la suggerisce fra le pause dolci delle pasticcerie del centro.'},{icon:'🍰',name:'Dolci agli agrumi e mandorle',description:'La pasticceria locale valorizza ingredienti del sud-est; ricette e disponibilità variano da laboratorio a laboratorio.'}], 'Corso Vittorio Emanuele cambia con la luce: il tardo pomeriggio esalta il colore caldo della pietra.','https://www.visitsicily.info/en/noto/'),
marzamemi:simple('Borgo marinaro del sud-est',[{icon:'🐟',name:'Tonno e conserve ittiche',description:'Il borgo è legato storicamente alla tonnara; preferisci prodotti con provenienza chiaramente indicata.'},{icon:'🍅',name:'Pomodoro di Pachino e cucina locale',description:'Ingrediente fortemente associato al territorio circostante, da incontrare in preparazioni semplici e stagionali.'}], 'La piazza è più suggestiva quando il flusso della giornata rallenta; esplora anche i passaggi verso il mare.','https://www.visitsicily.info/en/itinerario/following-the-bluefin-tuna-on-their-route-from-favignana-to-mondello/'),
ragusa:simple('Due città, un paesaggio ibleo',[{icon:'🥟',name:'Scacce ragusane',description:'Sottili sfoglie ripiene e ripiegate, diffuse da Ragusa Ibla a Modica e Scicli.'},{icon:'🧀',name:'Caciocavallo',description:'Formaggio vaccino tradizionale dell’area iblea, citato dalla guida regionale fra gli assaggi del Ragusano.'}], 'Alterna i belvedere alle discese: le distanze verticali contano più di quanto suggerisca la mappa.','https://www.visitsicily.info/en/localita/ragusa/'),
'ragusa-ibla':simple('Barocco e giardini nel cuore ibleo',[{icon:'🥟',name:'Scacce ragusane',description:'Una specialità dell’intero territorio ibleo, con ripieni che variano per stagione e tradizione familiare.'},{icon:'🧀',name:'Caciocavallo ragusano',description:'Da cercare come prodotto del territorio, verificando stagionatura e provenienza.'}], 'Percorri Ibla dal basso verso il Duomo e concediti una pausa nel Giardino Ibleo.','https://www.visitsicily.info/en/ricetta/le-scacce-ragusane/'),
modica:simple('Scale barocche e cultura del cacao',[{icon:'🍫',name:'Cioccolato di Modica',description:'Lavorato senza concaggio, conserva una consistenza granulosa caratteristica; è il prodotto simbolo della città.'},{icon:'🥟',name:'Scaccia',description:'Street food del territorio ibleo, ripieno e ripiegato in più strati.'}], 'Assaggia il cioccolato confrontando aromi semplici, poi risali verso San Giorgio: gusto e paesaggio urbano si spiegano insieme.','https://www.visitsicily.info/sapore/cioccolato-di-modica/'),
scicli:simple('Pietra, cave e piazze del sud-est',[{icon:'🥟',name:'Scacce',description:'Diffuse in tutto il territorio ibleo, si trovano nei forni con ripieni diversi.'},{icon:'🍪',name:'Dolci di mandorla',description:'Parte della tradizione dolciaria del sud-est, non esclusiva della singola città.'}], 'Via Mormina Penna rende al meglio con una passeggiata lenta; guarda anche i prospetti dalle strade laterali.','https://www.visitsicily.info/en/ricetta/le-scacce-ragusane/'),
agrigento:simple('Templi, luce e paesaggio',[{icon:'🌰',name:'Dolci di mandorla',description:'La mandorla è un riferimento ricorrente del territorio agrigentino e delle sue manifestazioni culturali.'},{icon:'🐟',name:'Cucina costiera',description:'Nelle località marine della provincia sono diffuse preparazioni di pesce; chiedi sempre provenienza e stagionalità.'}], 'Alla Valle dei Templi la luce del tardo pomeriggio è magnifica, ma verifica orari e accessi prima della visita.','https://www.visitsicily.info/wp-content/uploads/2026/04/Brochure_emozione_autentica_ITA_2026.pdf'),
trapani:simple('Fra due mari, saline e centro storico',[{icon:'🥣',name:'Cous cous di pesce',description:'Uno dei piatti simbolo del Trapanese e del dialogo gastronomico mediterraneo.'},{icon:'🍝',name:'Pasta cu l’agghia',description:'La cucina trapanese valorizza il pesto con aglio rosso di Nubia, pomodoro e mandorle.'}], 'Abbina il centro alle saline verso il tramonto, quando il paesaggio racconta anche l’importanza del sale marino.','https://www.visitsicily.info/en/localita/trapani/'),
favignana:simple('Cale chiare e memoria della tonnara',[{icon:'🐟',name:'Tonno',description:'La storia dell’isola è legata alla tonnara Florio; Visit Sicily segnala preparazioni fresche e conservate, dalla bottarga ai prodotti sott’olio.'}], 'Visita l’ex Stabilimento Florio per capire il prodotto prima di assaggiarlo; al mare rispetta sempre sentieri e accessi.','https://www.visitsicily.info/en/itinerario/following-the-bluefin-tuna-on-their-route-from-favignana-to-mondello/'),
'san-vito-lo-capo':simple('Spiaggia e culture del Mediterraneo',[{icon:'🥣',name:'Cous cous',description:'Il paese ospita il Cous Cous Fest e celebra questo piatto come ponte fra culture mediterranee, spesso in versione di pesce.'}], 'La spiaggia è protagonista, ma una passeggiata serale nel centro completa bene la giornata.','https://www.visitsicily.info/en/sapore/cous-cous-2/'),
erice:simple('Pietra medievale sopra il mare',[{icon:'🥧',name:'Genovese ericina',description:'Dolce ripieno di crema, spolverato di zucchero e tradizionalmente servito caldo.'},{icon:'🌰',name:'Pasticceria di mandorla',description:'Le ricette dei conventi hanno lasciato una tradizione di marzapane e biscotti nel borgo.'}], 'La nebbia può cambiare completamente l’atmosfera; porta uno strato in più anche quando sulla costa fa caldo.','https://www.visitsicily.info/en/erice/')
};

export const poiGuideContent: Record<string, PoiGuideContent> = {
  "pescheria-di-catania": {
    shortIntro: "Storico mercato del pesce accanto a Piazza Duomo, ancora legato alla vita quotidiana e alla tradizione commerciale del centro.",
    description: "",
    whyVisit: "È uno dei luoghi più immediati per percepire la Catania popolare, rumorosa e gastronomica oltre i monumenti.",
    whatToSee: "Guarda i banchi, le arcate in pietra lavica, i passaggi verso Piazza Alonzo di Benedetto e il rapporto con il Duomo.",
    practicalTips: "Meglio passarci al mattino, quando il mercato è più vivo; muoviti senza intralciare chi lavora.",
    sourceLabel: "Comune di Catania - Turismo",
    sourceUrl: "https://turismo.comune.catania.it/",
  },
  "fontana-dellelefante-u-liotru": {
    shortIntro: "La fontana al centro di Piazza Duomo è il simbolo civico di Catania: l'elefante in pietra lavica regge un obelisco antico.",
    description: "",
    whyVisit: "Racchiude in un solo monumento l'immagine più riconoscibile della città e il soprannome tradizionale 'Liotru'.",
    whatToSee: "Osserva il contrasto tra pietra lavica, marmo chiaro, obelisco e facciate barocche che chiudono la piazza.",
    practicalTips: "Guardala da più lati della piazza: la prospettiva cambia molto avvicinandosi alla Cattedrale.",
    sourceLabel: "Comune di Catania - Turismo",
    sourceUrl: "https://turismo.comune.catania.it/",
  },
  "via-crociferi": {
    shortIntro: "Una delle strade barocche più scenografiche di Catania, caratterizzata da una sequenza ravvicinata di chiese e conventi.",
    description: "",
    whyVisit: "È una sintesi molto compatta del volto ricostruito della città dopo il terremoto del 1693.",
    whatToSee: "Fermati sulle facciate, sui portali, sulle scalinate e sull'arco di San Benedetto; il valore è soprattutto nell'insieme urbano.",
    practicalTips: "Percorrila lentamente e, se trovi chiese aperte, entra senza trasformare la visita in una corsa tra interni.",
    sourceLabel: "Comune di Catania - Turismo",
    sourceUrl: "https://turismo.comune.catania.it/",
  },
  "piazza-universita": {
    shortIntro: "Piazza barocca lungo Via Etnea, definita da palazzi monumentali e collegata direttamente al cuore di Piazza Duomo.",
    description: "",
    whyVisit: "È una tappa breve ma utile per leggere la continuità urbanistica del centro storico catanese.",
    whatToSee: "Guarda le facciate dei palazzi e i candelabri con scene legate alle leggende cittadine.",
    practicalTips: "Usala come pausa tra Duomo e Via Etnea: pochi minuti bastano, ma vale la pena osservarla da entrambi gli assi.",
    sourceLabel: "Comune di Catania - Turismo",
    sourceUrl: "https://turismo.comune.catania.it/",
  },
  "teatro-massimo-bellini": {
    shortIntro: "Il principale teatro lirico di Catania, dedicato al compositore Vincenzo Bellini e inaugurato alla fine dell'Ottocento.",
    description: "",
    whyVisit: "Collega la tradizione musicale della città a uno dei suoi edifici civili più eleganti.",
    whatToSee: "Osserva la facciata, la piazza e, se accessibile, la sala a ferro di cavallo con decorazioni dedicate a Bellini.",
    practicalTips: "Se vuoi vedere l'interno, verifica in anticipo visite e programmazione sul sito ufficiale.",
    sourceLabel: "Teatro Massimo Bellini - sito ufficiale",
    sourceUrl: "https://www.teatromassimobellini.it/il-teatro-massimo-bellini/",
  },
  "via-etnea": {
    shortIntro: "L'asse urbano più famoso di Catania attraversa il centro storico con una lunga prospettiva che, nelle giornate limpide, dialoga con l'Etna.",
    description: "",
    whyVisit: "È la passeggiata che unisce monumenti, negozi, piazze e vita quotidiana in un unico percorso.",
    whatToSee: "Guarda la pavimentazione scura, i palazzi barocchi, le aperture sulle piazze e le prospettive verso il vulcano.",
    practicalTips: "Non viverla solo come trasferimento: procedi a tratti e voltati spesso per cambiare prospettiva.",
    sourceLabel: "Comune di Catania - Turismo",
    sourceUrl: "https://turismo.comune.catania.it/",
  },
  "giardino-bellini-villa-bellini": {
    shortIntro: "Grande giardino storico nel centro di Catania, disposto su terrazze e viali alberati lungo Via Etnea.",
    description: "",
    whyVisit: "È una pausa verde dopo il percorso monumentale e offre un cambio di ritmo rispetto alle strade del centro.",
    whatToSee: "Cerca i viali scenografici, le aiuole, le scalinate e i punti più alti da cui leggere il profilo urbano.",
    practicalTips: "Ottimo per una sosta nel pomeriggio; in estate cerca le zone ombreggiate e porta acqua.",
    sourceLabel: "Comune di Catania - Turismo",
    sourceUrl: "https://turismo.comune.catania.it/",
  },
  "duomo-di-taormina": {
    shortIntro: "La Cattedrale di San Nicolò si affaccia su Piazza Duomo con un aspetto severo, quasi fortificato, accanto alla fontana barocca.",
    description: "",
    whyVisit: "Mostra il lato medievale di Taormina, spesso oscurato dalla fama del Teatro Antico e dei panorami.",
    whatToSee: "Osserva merlature, portale, rosone e il contrasto con la fontana delle Quattro Fontane nella piazza.",
    practicalTips: "Entrando, mantieni una visita breve e rispettosa; poi guarda la facciata dalla parte opposta della piazza.",
    sourceLabel: "Visit Sicily - Taormina",
    sourceUrl: "https://www.visitsicily.info/localita/taormina/",
  },
  "corso-umberto": {
    shortIntro: "La principale passeggiata pedonale di Taormina collega Porta Messina e Porta Catania attraversando il centro storico.",
    description: "",
    whyVisit: "È il filo conduttore della città: lungo pochi isolati concentra piazze, palazzi, chiese, botteghe e scorci.",
    whatToSee: "Guarda i vicoli laterali, i balconi, le aperture panoramiche e come cambiano le facciate lungo il percorso.",
    practicalTips: "Percorrilo almeno una volta senza fretta; al mattino è più leggibile, la sera è più atmosferico.",
    sourceLabel: "Visit Sicily - Taormina",
    sourceUrl: "https://www.visitsicily.info/localita/taormina/",
  },
  "palazzo-corvaja": {
    shortIntro: "Complesso storico vicino a Porta Messina, con stratificazioni medievali e influenze arabe, normanne e gotiche.",
    description: "",
    whyVisit: "È uno dei migliori esempi della storia architettonica composita di Taormina.",
    whatToSee: "Osserva la torre, il cortile, le finestre ad arco e i rilievi; Visit Sicily ricorda anche il ruolo del palazzo nel Parlamento siciliano del Quattrocento.",
    practicalTips: "Bastano pochi minuti all'esterno, ma verifica se gli ambienti interni o gli spazi espositivi sono visitabili.",
    sourceLabel: "Visit Sicily - Taormina",
    sourceUrl: "https://www.visitsicily.info/localita/taormina/",
  },
  "teatro-antico-di-taormina": {
    shortIntro: "Teatro di origine ellenistica profondamente trasformato in età romana, costruito in posizione panoramica sopra il mare Ionio.",
    description: "",
    whyVisit: "Unisce archeologia e paesaggio in modo eccezionale: la scena inquadra Etna, costa e mare.",
    whatToSee: "Guarda cavea, edificio scenico, aperture tra le strutture e soprattutto il rapporto fra monumento e panorama.",
    practicalTips: "Dedica almeno un'ora e verifica orari/eventuali limitazioni sul sito del Parco Archeologico prima di partire.",
    sourceLabel: "Parco Archeologico di Naxos e Taormina",
    sourceUrl: "https://parchiarcheologici.regione.sicilia.it/naxos-taormina/siti-archeologici/teatro-antico-di-taormina/",
  },
  "villa-comunale-di-taormina": {
    shortIntro: "Giardino pubblico nato dall'antico parco di Lady Florence Trevelyan, con vegetazione, terrazze e costruzioni eccentriche.",
    description: "",
    whyVisit: "È un bel punto di pausa e uno dei luoghi più piacevoli per osservare la costa lontano dal flusso di Corso Umberto.",
    whatToSee: "Cerca le particolari 'Victorian follies', i belvedere, la vegetazione mediterranea e le vedute sul mare.",
    practicalTips: "Inseriscila tra Teatro Antico e Isola Bella: una sosta breve qui aiuta a spezzare la parte più intensa della giornata.",
    sourceLabel: "Visit Sicily - Taormina",
    sourceUrl: "https://www.visitsicily.info/localita/taormina/",
  },
  "isola-bella": {
    shortIntro: "Piccola isola e area naturale ai piedi di Taormina, collegata alla costa da una sottile lingua di ciottoli che varia con il mare.",
    description: "",
    whyVisit: "È il contrappunto naturale alla Taormina monumentale: acqua, costa rocciosa e vegetazione mediterranea.",
    whatToSee: "Guarda il profilo dell'isola dalla spiaggia, le trasparenze dell'acqua e la costa vista dal livello del mare.",
    practicalTips: "Porta scarpe adatte ai ciottoli e verifica mare, accessi e regolamentazione dell'area prima della discesa.",
    sourceLabel: "Parco Archeologico di Naxos e Taormina - Isola Bella",
    sourceUrl: "https://parchiarcheologici.regione.sicilia.it/naxos-taormina/siti-archeologici/",
  },
  "escursione-etna": {
    shortIntro: "L'Etna è il più alto vulcano attivo d'Europa e un sito UNESCO, con paesaggi modellati da colate, crateri e vegetazione pioniera.",
    description: "",
    whyVisit: "Camminare sul vulcano permette di leggere direttamente un territorio in continua trasformazione.",
    whatToSee: "Osserva differenze tra lave recenti e più antiche, crateri, materiali vulcanici e cambiamenti della vegetazione con quota ed esposizione.",
    practicalTips: "Segui sempre guida e indicazioni ufficiali, porta scarpe chiuse e strati antivento e considera che meteo e accessi possono cambiare rapidamente.",
    sourceLabel: "UNESCO - Mount Etna",
    sourceUrl: "https://whc.unesco.org/en/list/1427/",
  },
  "trasferimento-etna-siracusa": {
    shortIntro: "Tratta operativa che collega l'ambiente vulcanico dell'Etna alla costa sud-orientale e a Siracusa.",
    description: "",
    whyVisit: "Segna un vero cambio di paesaggio e prepara la parte archeologica e barocca del viaggio.",
    whatToSee: "Durante il percorso nota il passaggio dalle pendici vulcaniche alla piana e poi all'area costiera siracusana.",
    practicalTips: "Trattala come trasferimento, non come visita: controlla traffico, carburante e arrivo prima di partire.",
    sourceLabel: "Visit Sicily - Siracusa",
    sourceUrl: "https://www.visitsicily.info/localita/siracusa/",
  },
  "parco-archeologico-orecchio-di-dionisio-teatro-greco": {
    shortIntro: "Il Parco della Neapolis concentra il Teatro Greco, le latomie e l'Orecchio di Dionisio, tra i nuclei archeologici più importanti di Siracusa.",
    description: "",
    whyVisit: "In una sola visita mette insieme storia greca e romana, cave di pietra e trasformazioni del paesaggio antico.",
    whatToSee: "Concentrati sulla cavea del Teatro Greco, sulla scala del taglio nella roccia e sulla forma/acustica dell'Orecchio di Dionisio.",
    practicalTips: "È una visita esposta al sole: acqua, cappello e scarpe comode sono più utili di una tabella di marcia troppo stretta.",
    sourceLabel: "Parco Archeologico di Siracusa",
    sourceUrl: "https://parchiarcheologici.regione.sicilia.it/parco-archeologico-di-siracusa-eloro-villa-del-tellaro-e-akrai/",
  },
  "basilica-santuario-madonna-delle-lacrime": {
    shortIntro: "Santuario moderno dalla grande struttura conica, costruito per custodire la memoria del fenomeno religioso delle lacrimazioni del 1953.",
    description: "",
    whyVisit: "Offre un forte contrasto con l'archeologia e il barocco di Siracusa e mostra un volto contemporaneo della città.",
    whatToSee: "Guarda l'impianto circolare, la luce interna, l'altezza della copertura e il rapporto con la vicina area archeologica.",
    practicalTips: "È un luogo di culto attivo: evita gli orari delle celebrazioni se vuoi una visita più tranquilla.",
    sourceLabel: "Visit Sicily - Siracusa",
    sourceUrl: "https://www.visitsicily.info/localita/siracusa/",
  },
  "tempio-di-apollo": {
    shortIntro: "Resti di uno dei più antichi templi dorici in pietra della Sicilia, immediatamente visibili entrando a Ortigia.",
    description: "",
    whyVisit: "È un'introduzione perfetta alla profondità storica dell'isola: il monumento è inglobato nel tessuto urbano moderno.",
    whatToSee: "Osserva le colonne superstiti, il podio e il contrasto tra rovina archeologica, mercato e edifici circostanti.",
    practicalTips: "La visita è soprattutto esterna e rapida: sfrutta il punto per orientarti prima di entrare nel cuore di Ortigia.",
    sourceLabel: "Visit Sicily - Siracusa",
    sourceUrl: "https://www.visitsicily.info/localita/siracusa/",
  },
  "fontana-di-diana": {
    shortIntro: "Fontana monumentale di Piazza Archimede dedicata al mito di Aretusa, Artemide/Diana e Alfeo.",
    description: "",
    whyVisit: "Porta la mitologia siracusana nel centro della vita urbana di Ortigia.",
    whatToSee: "Guarda il gruppo scultoreo centrale e come la composizione racconta il mito da più angolazioni.",
    practicalTips: "Fai un giro completo della fontana: la lettura migliore non è da un solo lato.",
    sourceLabel: "Visit Sicily - Siracusa",
    sourceUrl: "https://www.visitsicily.info/localita/siracusa/",
  },
  "piazza-duomo-cattedrale": {
    shortIntro: "Piazza Duomo è il grande spazio barocco di Ortigia; la Cattedrale incorpora nella propria struttura le colonne dell'antico tempio di Atena.",
    description: "",
    whyVisit: "È uno dei luoghi dove la stratificazione di Siracusa è più evidente: mondo greco, cristianesimo e barocco convivono nello stesso edificio.",
    whatToSee: "Guarda la facciata barocca e, all'interno, cerca le colonne doriche inglobate nelle pareti della navata.",
    practicalTips: "Entra quando non sono in corso funzioni e poi percorri la piazza fino alle estremità per apprezzarne la forma.",
    sourceLabel: "Visit Sicily - Siracusa",
    sourceUrl: "https://www.visitsicily.info/localita/siracusa/",
  },
  "fonte-aretusa": {
    shortIntro: "Sorgente d'acqua dolce sul lungomare di Ortigia, legata al mito di Aretusa e caratterizzata dalla presenza del papiro.",
    description: "",
    whyVisit: "È una tappa breve che lega paesaggio, mito e una peculiarità botanica rara nel cuore della città.",
    whatToSee: "Osserva il papiro, la vasca, gli uccelli acquatici e l'apertura immediata verso il mare.",
    practicalTips: "Passaci verso il tardo pomeriggio: è naturale proseguire da qui sul Lungomare Alfeo.",
    sourceLabel: "Visit Sicily - Siracusa",
    sourceUrl: "https://www.visitsicily.info/localita/siracusa/",
  },
  "lungomare-alfeo-ortigia": {
    shortIntro: "Passeggiata sul margine occidentale di Ortigia, tra mura, mare, piccoli approdi e facciate rivolte al porto.",
    description: "",
    whyVisit: "È il modo migliore per chiudere una giornata monumentale con una lettura più lenta e marittima della città.",
    whatToSee: "Guarda i riflessi sull'acqua, le fortificazioni, i vicoli che risalgono verso il centro e il profilo della costa.",
    practicalTips: "Tienilo per la golden hour o per la sera, quando la luce e la temperatura rendono il percorso più piacevole.",
    sourceLabel: "Visit Sicily - Siracusa",
    sourceUrl: "https://www.visitsicily.info/localita/siracusa/",
  },
  "pillirina-boat-tour": {
    shortIntro: "Escursione costiera nell'area della Pillirina e del Plemmirio, caratterizzata da falesie, calette e acqua limpida.",
    description: "",
    whyVisit: "Dal mare si legge una parte della costa siracusana che a terra è più frammentata e difficile da percepire nel suo insieme.",
    whatToSee: "Osserva profilo roccioso, grotte e trasparenze dell'acqua, oltre ai cambiamenti del fondale vicino costa.",
    practicalTips: "Segui le regole dell'Area Marina Protetta e le indicazioni dell'operatore; vento e mare contano più dell'orario teorico.",
    sourceLabel: "Italia.it - Pillirina",
    sourceUrl: "https://www.italia.it/it/sicilia/siracusa/pillirina",
  },
  "porta-reale-noto": {
    shortIntro: "Arco monumentale ottocentesco che introduce al Corso Vittorio Emanuele e al percorso storico di Noto.",
    description: "",
    whyVisit: "Funziona come vera soglia scenografica: dopo l'arco si apre progressivamente il grande asse barocco della città.",
    whatToSee: "Guarda le decorazioni simboliche dell'arco e soprattutto la prospettiva del Corso che si apre oltre la porta.",
    practicalTips: "È una tappa da pochi minuti: usala come inizio naturale della visita a piedi.",
    sourceLabel: "Comune di Noto - Turismo",
    sourceUrl: "https://www.comune.noto.sr.it/it/topics/turismo",
  },
  "san-francesco-allimmacolata-noto": {
    shortIntro: "Chiesa barocca preceduta da un'ampia scalinata, lungo il primo tratto monumentale di Corso Vittorio Emanuele.",
    description: "",
    whyVisit: "Mostra bene il rapporto tra architettura religiosa e spazio urbano nella Noto ricostruita dopo il 1693.",
    whatToSee: "Osserva scalinata, facciata e come la chiesa si inserisce nella sequenza prospettica del corso.",
    practicalTips: "Se è aperta, entra brevemente; all'esterno allontanati fino al bordo opposto della strada per leggere l'insieme.",
    sourceLabel: "Comune di Noto - Turismo",
    sourceUrl: "https://www.comune.noto.sr.it/it/topics/turismo",
  },
  "cattedrale-di-noto": {
    shortIntro: "La Cattedrale di San Nicolò domina Piazza Municipio ed è uno dei simboli della ricostruzione barocca di Noto.",
    description: "",
    whyVisit: "La sua grande scalinata e la facciata color miele definiscono l'immagine più riconoscibile della città.",
    whatToSee: "Guarda i due campanili, la scalinata, la facciata e il dialogo frontale con Palazzo Ducezio.",
    practicalTips: "Osservala anche dalla terrazza o dal lato opposto della piazza; verifica eventuali celebrazioni prima di entrare.",
    sourceLabel: "Comune di Noto - Cattedrale di San Nicolò",
    sourceUrl: "https://www.comune.noto.sr.it/it/vivere/cattedrale-di-san-nicolo",
  },
  "palazzo-ducezio": {
    shortIntro: "Sede municipale di Noto, progettata nel Settecento e disposta di fronte alla Cattedrale.",
    description: "",
    whyVisit: "Completa la scenografia di Piazza Municipio e rappresenta il volto civile del barocco netino.",
    whatToSee: "Osserva il portico curvo, il ritmo delle colonne e la relazione prospettica con la scalinata della Cattedrale.",
    practicalTips: "Verifica se gli ambienti visitabili e la terrazza sono accessibili: condizioni e biglietti possono cambiare.",
    sourceLabel: "Comune di Noto - Turismo",
    sourceUrl: "https://www.comune.noto.sr.it/it/topics/turismo",
  },
  "via-corrado-nicolaci": {
    shortIntro: "Strada in salita celebre per i balconi barocchi di Palazzo Nicolaci e per l'Infiorata che la trasforma ogni primavera.",
    description: "",
    whyVisit: "È uno dei punti migliori per osservare da vicino la fantasia decorativa della pietra di Noto.",
    whatToSee: "Guarda mensole scolpite, balconi in ferro, mascheroni e la prospettiva ripida verso la chiesa di Montevergine.",
    practicalTips: "Percorrila prima dal basso verso l'alto, poi voltati: la prospettiva inversa valorizza molto i balconi.",
    sourceLabel: "Comune di Noto - Turismo",
    sourceUrl: "https://www.comune.noto.sr.it/it/topics/turismo",
  },
  "teatro-tina-di-lorenzo": {
    shortIntro: "Elegante teatro comunale ottocentesco affacciato su Piazza XVI Maggio, intitolato all'attrice Tina Di Lorenzo.",
    description: "",
    whyVisit: "Aggiunge alla Noto barocca un capitolo più tardo legato alla vita culturale e teatrale della città.",
    whatToSee: "Guarda la facciata e, se accessibile, la sala interna con palchi e decorazioni.",
    practicalTips: "Controlla sul sito del Comune visite e spettacoli: l'interno vale più della sola sosta esterna.",
    sourceLabel: "Comune di Noto - Teatro Tina Di Lorenzo",
    sourceUrl: "https://www.comune.noto.sr.it/index.php/it/vivere/755130",
  },
  "chiesa-di-san-domenico": {
    shortIntro: "Capolavoro barocco di Rosario Gagliardi affacciato su Piazza XVI Maggio, con facciata convessa e forte movimento plastico.",
    description: "",
    whyVisit: "È uno degli edifici che meglio esprimono il linguaggio del tardo barocco del Val di Noto.",
    whatToSee: "Osserva la curvatura della facciata, colonne e nicchie, poi confrontala con il teatro sul lato opposto della piazza.",
    practicalTips: "Fermati al centro della piazza: è il punto migliore per leggere insieme chiesa, spazio urbano e teatro.",
    sourceLabel: "Comune di Noto - Turismo",
    sourceUrl: "https://www.comune.noto.sr.it/it/topics/turismo",
  },
  "transfer-noto-marzamemi": {
    shortIntro: "Breve trasferimento dall'altopiano barocco di Noto al borgo marinaro di Marzamemi.",
    description: "",
    whyVisit: "In poco tempo cambia completamente il paesaggio: dalla pietra calcarea delle città storiche al mare e alla tradizione della tonnara.",
    whatToSee: "Durante l'arrivo nota il passaggio verso la campagna costiera e l'apertura sul mare.",
    practicalTips: "Lascia un piccolo margine per parcheggio e accesso pedonale al borgo, soprattutto nel tardo pomeriggio.",
    sourceLabel: "Comune di Noto - Turismo",
    sourceUrl: "https://www.comune.noto.sr.it/it/topics/turismo",
  },
  "tonnara-di-marzamemi": {
    shortIntro: "La tonnara è il nucleo storico che racconta la lunga relazione di Marzamemi con la pesca e la lavorazione del tonno.",
    description: "",
    whyVisit: "Permette di capire il borgo oltre la sua immagine da cartolina e lega piazza, case dei pescatori e attività marinare.",
    whatToSee: "Guarda gli edifici della tonnara, gli antichi spazi di lavoro e la loro relazione con il porto e Piazza Regina Margherita.",
    practicalTips: "Anche se alcuni spazi sono privati o usati per eventi, l'insieme si legge bene passeggiando all'esterno.",
    sourceLabel: "Visit Sicily - Marzamemi",
    sourceUrl: "https://www.visitsicily.info/en/marzamemi/",
  },
  "piazza-regina-margherita": {
    shortIntro: "Piazza principale di Marzamemi, circondata da edifici chiari, case dei pescatori e strutture legate alla tonnara.",
    description: "",
    whyVisit: "È il cuore sociale e visivo del borgo e concentra l'atmosfera che rende Marzamemi riconoscibile.",
    whatToSee: "Guarda le due chiese, le facciate semplici, i tavolini e i passaggi laterali verso il mare.",
    practicalTips: "Arriva prima del tramonto per vederla con luce naturale e poi restare quando si accendono le luci.",
    sourceLabel: "Visit Sicily - Marzamemi",
    sourceUrl: "https://www.visitsicily.info/en/marzamemi/",
  },
  "vicolo-delle-sirene-sunset": {
    shortIntro: "Passeggiata tra i vicoli del borgo e la fascia costiera di Marzamemi, pensata come chiusura lenta della giornata.",
    description: "",
    whyVisit: "Qui il valore non è un singolo monumento ma l'atmosfera tra case, mare e luce del tramonto.",
    whatToSee: "Cerca scorci tra le case, dettagli marinari, piccole aperture sul porto e riflessi della luce sulle facciate.",
    practicalTips: "Non inseguire un punto preciso: tieni tempo libero e spostati dove la luce è migliore.",
    sourceLabel: "Visit Sicily - Marzamemi",
    sourceUrl: "https://www.visitsicily.info/en/marzamemi/",
  },
  "cattedrale-san-giovanni-battista-ragusa": {
    shortIntro: "Grande cattedrale barocca di Ragusa Superiore, ricostruita dopo il terremoto del 1693 e affacciata sull'ampia piazza omonima.",
    description: "",
    whyVisit: "Introduce il volto della città alta prima della discesa verso Ragusa Ibla e mostra una diversa scala urbana rispetto al quartiere antico.",
    whatToSee: "Guarda la facciata, la scalinata, la cupola e l'ampiezza dello spazio davanti all'edificio.",
    practicalTips: "Osservala prima da lontano lungo l'asse della piazza e poi avvicinati ai dettagli della facciata.",
    sourceLabel: "Visit Sicily - Ragusa",
    sourceUrl: "https://www.visitsicily.info/localita/ragusa/",
  },
  "santa-maria-delle-scale": {
    shortIntro: "Chiesa posta sul margine tra Ragusa Superiore e Ibla, in un punto naturalmente panoramico sulla città antica.",
    description: "",
    whyVisit: "È una delle tappe più utili per capire fisicamente il rapporto tra i due nuclei urbani di Ragusa.",
    whatToSee: "Guarda il panorama su Ibla, la scalinata e le parti architettoniche che testimoniano fasi precedenti e successive al terremoto.",
    practicalTips: "Fermati qui prima della discesa: la vista aiuta a orientarsi e a riconoscere il percorso che farai a piedi.",
    sourceLabel: "Visit Sicily - Ragusa",
    sourceUrl: "https://www.visitsicily.info/localita/ragusa/",
  },
  "santa-maria-dellitria": {
    shortIntro: "Chiesa barocca di Ragusa riconoscibile soprattutto per il campanile decorato con maioliche colorate.",
    description: "",
    whyVisit: "È un dettaglio urbano molto caratteristico lungo la discesa verso Ibla.",
    whatToSee: "Guarda il campanile, la cupola rivestita e il modo in cui emerge tra gli edifici e i vicoli circostanti.",
    practicalTips: "Il punto di vista cambia molto lungo le scale: voltati più volte mentre scendi.",
    sourceLabel: "Visit Sicily - Ragusa",
    sourceUrl: "https://www.visitsicily.info/localita/ragusa/",
  },
  "piazza-duomo-duomo-san-giorgio-ragusa-ibla": {
    shortIntro: "Il Duomo di San Giorgio domina la piazza principale di Ragusa Ibla con la sua facciata barocca e la cupola elevata sul tessuto urbano.",
    description: "",
    whyVisit: "È il fulcro monumentale di Ibla e uno dei simboli del tardo barocco del Val di Noto.",
    whatToSee: "Guarda la facciata posta in diagonale rispetto alla piazza, la scalinata, la cupola e la continuità con i palazzi circostanti.",
    practicalTips: "Fermati anche nella parte bassa della piazza: la distanza rende più leggibile l'intera composizione.",
    sourceLabel: "Visit Sicily - Ragusa Ibla",
    sourceUrl: "https://www.visitsicily.info/attrazione/ragusa-ibla-il-cuore-barocco-della-citta/",
  },
  "circolo-di-conversazione": {
    shortIntro: "Piccolo edificio ottocentesco di Ragusa Ibla, nato come luogo di ritrovo della borghesia locale.",
    description: "",
    whyVisit: "È una deviazione interessante perché racconta la vita sociale della città oltre chiese e palazzi barocchi.",
    whatToSee: "Osserva la facciata neoclassica e, se accessibile, gli ambienti interni decorati.",
    practicalTips: "È una visita breve: verifica sul posto l'accessibilità prima di inserirla rigidamente nella tabella di marcia.",
    sourceLabel: "Visit Sicily - Ragusa",
    sourceUrl: "https://www.visitsicily.info/localita/ragusa/",
  },
  "giardino-ibleo": {
    shortIntro: "Giardino pubblico storico all'estremità orientale di Ragusa Ibla, con viali, palme e affacci sulla vallata.",
    description: "",
    whyVisit: "Offre una pausa verde e una prospettiva diversa sul paesaggio ibleo dopo il centro monumentale.",
    whatToSee: "Guarda i viali, le chiese all'interno del giardino e i belvedere verso le vallate.",
    practicalTips: "Perfetto per una sosta breve con acqua e ombra prima di riprendere l'auto.",
    sourceLabel: "Visit Sicily - Ragusa",
    sourceUrl: "https://www.visitsicily.info/localita/ragusa/",
  },
  "duomo-san-giorgio-modica": {
    shortIntro: "San Giorgio domina Modica Alta con una lunga scalinata e una scenografica facciata tardo barocca.",
    description: "",
    whyVisit: "È il monumento che meglio rende visibile la verticalità di Modica, costruita su pendii e terrazze.",
    whatToSee: "Guarda la scalinata, i livelli della facciata, il campanile e la vista sulla città dal sagrato.",
    practicalTips: "Calcola qualche minuto in più per la salita: il colpo d'occhio migliora man mano che guadagni quota.",
    sourceLabel: "Visit Sicily - Modica",
    sourceUrl: "https://www.visitsicily.info/modica/",
  },
  "belvedere-san-benedetto": {
    shortIntro: "Punto panoramico sulle case, chiese e pendii di Modica, utile per leggere la particolare struttura verticale della città.",
    description: "",
    whyVisit: "Dopo aver camminato nelle strade, offre la visione d'insieme che rende comprensibile il rapporto tra Modica Alta e Bassa.",
    whatToSee: "Individua il Duomo di San Giorgio, le case stratificate sui versanti e l'asse della città bassa.",
    practicalTips: "Se la luce è dura, una sosta più tardi nel pomeriggio restituisce meglio i volumi della città.",
    sourceLabel: "Visit Sicily - Modica",
    sourceUrl: "https://www.visitsicily.info/modica/",
  },
  "corso-umberto-i": {
    shortIntro: "Asse principale di Modica Bassa, fiancheggiato da palazzi, chiese, caffè e botteghe.",
    description: "",
    whyVisit: "È la passeggiata che restituisce il lato più quotidiano di Modica e collega molte delle sue tappe principali.",
    whatToSee: "Guarda facciate, balconi e improvvise aperture verso scalinate e quartieri più alti.",
    practicalTips: "Percorrine un tratto a piedi senza un obiettivo preciso: è il modo migliore per scoprire deviazioni e scorci.",
    sourceLabel: "Visit Sicily - Modica",
    sourceUrl: "https://www.visitsicily.info/modica/",
  },
  "duomo-san-pietro": {
    shortIntro: "Chiesa barocca di Modica Bassa preceduta da una scalinata fiancheggiata dalle statue degli Apostoli.",
    description: "",
    whyVisit: "È il contrappunto urbano a San Giorgio e uno dei punti principali lungo Corso Umberto I.",
    whatToSee: "Guarda la scalinata, la serie degli Apostoli e la ricca facciata che emerge direttamente dal corso.",
    practicalTips: "Osservala prima dal lato opposto della strada; la distanza aiuta a leggere l'intera elevazione.",
    sourceLabel: "Visit Sicily - Modica",
    sourceUrl: "https://www.visitsicily.info/modica/",
  },
  "piazza-italia-scicli": {
    shortIntro: "Grande spazio urbano di Scicli circondato da edifici e chiese, punto naturale di orientamento nel centro storico.",
    description: "",
    whyVisit: "Aiuta a leggere il passaggio tra il tessuto quotidiano della città e le strade monumentali del barocco.",
    whatToSee: "Guarda le diverse facciate che definiscono la piazza e gli assi stradali che si aprono verso il centro.",
    practicalTips: "Usala come punto di pausa e orientamento prima di entrare in Via Mormina Penna.",
    sourceLabel: "Visit Sicily - Scicli",
    sourceUrl: "https://www.visitsicily.info/scicli-appunti-per-la-visita/",
  },
  "palazzo-beneventano": {
    shortIntro: "Uno dei palazzi barocchi più celebri di Scicli, noto per balconi e mensole scolpite con figure fantastiche e mascheroni.",
    description: "",
    whyVisit: "È un esempio particolarmente espressivo della fantasia decorativa del tardo barocco siciliano.",
    whatToSee: "Guarda da vicino mensole, volti, animali fantastici e il ritmo dei balconi agli angoli del palazzo.",
    practicalTips: "La luce radente valorizza le sculture: se puoi, evita il momento più piatto del mezzogiorno.",
    sourceLabel: "Visit Sicily - Scicli",
    sourceUrl: "https://www.visitsicily.info/scicli-appunti-per-la-visita/",
  },
  "via-francesco-mormina-penna": {
    shortIntro: "Elegante strada monumentale di Scicli su cui si affacciano chiese e palazzi inclusi nel contesto UNESCO del Val di Noto.",
    description: "",
    whyVisit: "È una passeggiata compatta che permette di vedere diversi edifici senza continui spostamenti.",
    whatToSee: "Guarda la successione delle facciate, Palazzo Spadaro, il Municipio e le chiese lungo l'asse.",
    practicalTips: "Percorrila lentamente in entrambe le direzioni: le facciate cambiano molto con la prospettiva.",
    sourceLabel: "Visit Sicily - Scicli",
    sourceUrl: "https://www.visitsicily.info/scicli-appunti-per-la-visita/",
  },
  "chiesa-san-giovanni-evangelista": {
    shortIntro: "Chiesa barocca di Via Mormina Penna, inserita nel cuore monumentale di Scicli.",
    description: "",
    whyVisit: "Completa la lettura della strada UNESCO e offre un interno più raccolto rispetto alle grandi facciate cittadine.",
    whatToSee: "Osserva la facciata sinuosa, il rapporto con la strada e, se aperta, le opere conservate all'interno.",
    practicalTips: "Verifica l'apertura senza modificare troppo il percorso: l'esterno resta comunque parte essenziale della visita.",
    sourceLabel: "Visit Sicily - Scicli",
    sourceUrl: "https://www.visitsicily.info/scicli-appunti-per-la-visita/",
  },
  "antica-farmacia-cartia": {
    shortIntro: "Farmacia storica di Scicli conservata come piccolo museo, con arredi, vasi e strumenti legati alla pratica farmaceutica del primo Novecento.",
    description: "",
    whyVisit: "È una tappa diversa dal barocco: racconta la vita quotidiana e professionale della città attraverso un ambiente rimasto molto caratterizzato.",
    whatToSee: "Guarda mobilio, contenitori, etichette e strumenti, più che cercare un singolo pezzo famoso.",
    practicalTips: "Essendo un piccolo spazio con accessi specifici, controlla giorni e modalità di visita prima di arrivare.",
    sourceLabel: "Visit Sicily - Scicli",
    sourceUrl: "https://www.visitsicily.info/scicli-appunti-per-la-visita/",
  },
  "chiesa-san-bartolomeo": {
    shortIntro: "Chiesa collocata in una scenografica gola ai margini del centro di Scicli, sopravvissuta in parte al terremoto del 1693.",
    description: "",
    whyVisit: "Il contesto paesaggistico la rende diversa dalle chiese allineate sulle strade barocche del centro.",
    whatToSee: "Guarda la facciata, la parete rocciosa alle spalle e il contrasto tra edificio e vallone.",
    practicalTips: "Avvicinati a piedi e prenditi qualche minuto per osservare anche il paesaggio circostante.",
    sourceLabel: "Visit Sicily - Scicli",
    sourceUrl: "https://www.visitsicily.info/scicli-appunti-per-la-visita/",
  },
  "valle-dei-templi": {
    shortIntro: "Ampia area archeologica dell'antica Akragas, colonia greca fondata nel VI secolo a.C. e patrimonio UNESCO.",
    description: "",
    whyVisit: "È uno dei complessi di templi dorici meglio conservati del Mediterraneo e la tappa archeologica principale del viaggio.",
    whatToSee: "Concentrati sui Templi della Concordia, Giunone e Ercole, ma osserva anche mura, necropoli e paesaggio agricolo.",
    practicalTips: "Il sito è esteso e molto esposto: acqua, cappello e scarpe comode; verifica accessi e orari ufficiali prima della visita.",
    sourceLabel: "UNESCO - Archaeological Area of Agrigento",
    sourceUrl: "https://whc.unesco.org/en/list/831/",
  },
  "statua-andrea-camilleri": {
    shortIntro: "Omaggio urbano ad Andrea Camilleri nel centro di Agrigento, inserito nel percorso cittadino legato alla letteratura siciliana.",
    description: "",
    whyVisit: "È una tappa breve che aggiunge al viaggio archeologico un riferimento alla cultura contemporanea dell'isola.",
    whatToSee: "Guarda il rapporto della statua con la strada e con la vita quotidiana che le scorre attorno.",
    practicalTips: "Considerala una sosta fotografica di pochi minuti lungo la passeggiata, non una visita autonoma.",
    sourceLabel: "Visit Sicily - Agrigento",
    sourceUrl: "https://www.visitsicily.info/localita/agrigento/",
  },
  "via-atenea": {
    shortIntro: "Principale passeggiata del centro storico di Agrigento, con negozi, palazzi, vicoli e salite verso la città alta.",
    description: "",
    whyVisit: "Mostra un volto di Agrigento molto diverso dalla Valle dei Templi e aiuta a collegare monumenti e vita urbana.",
    whatToSee: "Guarda i palazzi lungo il corso e soprattutto le stradine e scalinate che salgono lateralmente.",
    practicalTips: "Percorrila senza fretta nelle ore meno calde; le deviazioni laterali spesso regalano gli scorci migliori.",
    sourceLabel: "Visit Sicily - Agrigento",
    sourceUrl: "https://www.visitsicily.info/localita/agrigento/",
  },
  "piazza-municipio": {
    shortIntro: "Spazio civico del centro di Agrigento collegato al Teatro Pirandello e agli edifici amministrativi storici.",
    description: "",
    whyVisit: "È una tappa di passaggio utile per leggere il cuore ottocentesco della città.",
    whatToSee: "Guarda l'ingresso del teatro, i prospetti degli edifici e le connessioni con Via Atenea.",
    practicalTips: "Usala come punto di orientamento prima di salire verso la Cattedrale.",
    sourceLabel: "Visit Sicily - Agrigento",
    sourceUrl: "https://www.visitsicily.info/localita/agrigento/",
  },
  "teatro-pirandello": {
    shortIntro: "Teatro storico di Agrigento intitolato a Luigi Pirandello, collocato nel complesso municipale.",
    description: "",
    whyVisit: "Ricorda il forte legame della città con il Nobel agrigentino e con la tradizione teatrale locale.",
    whatToSee: "Osserva facciata, foyer e sala se le visite sono disponibili.",
    practicalTips: "Controlla programmazione e accessibilità: se l'interno non è visitabile, mantieni la sosta breve.",
    sourceLabel: "Visit Sicily - Agrigento",
    sourceUrl: "https://www.visitsicily.info/localita/agrigento/",
  },
  "cattedrale-san-gerlando": {
    shortIntro: "Cattedrale medievale di Agrigento posta nella parte alta della città, più volte trasformata nel corso dei secoli.",
    description: "",
    whyVisit: "La salita vale sia per l'edificio sia per capire la stratificazione del centro storico lontano dalla Valle.",
    whatToSee: "Guarda facciata, campanile e gli elementi di epoche diverse accumulati nell'architettura.",
    practicalTips: "Raggiungila con scarpe comode e considera la pendenza; verifica eventuali funzioni religiose.",
    sourceLabel: "Visit Sicily - Agrigento",
    sourceUrl: "https://www.visitsicily.info/localita/agrigento/",
  },
  "scala-dei-turchi": {
    shortIntro: "Falesia bianca di marna sulla costa di Realmonte, modellata in forme a gradoni dal vento e dal mare.",
    description: "",
    whyVisit: "Il contrasto tra roccia chiarissima e Mediterraneo crea uno dei paesaggi costieri più riconoscibili della Sicilia.",
    whatToSee: "Osserva le stratificazioni della marna, la forma a gradoni e i cambi di colore con la luce.",
    practicalTips: "Rispetta recinzioni e divieti di accesso: la fruizione della falesia può essere regolata per ragioni di sicurezza.",
    sourceLabel: "Visit Sicily - Spiagge della Sicilia",
    sourceUrl: "https://www.visitsicily.info/spiagge-piu-belle-in-sicilia/",
  },
  "departure-agrigento": {
    shortIntro: "Tappa operativa che chiude la parte agrigentina e avvia il trasferimento verso la Sicilia occidentale.",
    description: "",
    whyVisit: "Serve a marcare il cambio di area del viaggio prima di Gibellina, Marsala e Trapani.",
    whatToSee: "Più che un monumento, qui conta controllare percorso, carburante e tempi reali di partenza.",
    practicalTips: "Parti con un po' di margine: la giornata contiene più soste e vale la pena non comprimere Cretto e saline.",
    sourceLabel: "Visit Sicily - Agrigento",
    sourceUrl: "https://www.visitsicily.info/localita/agrigento/",
  },
  "cretto-di-burri": {
    shortIntro: "Grande opera ambientale di Alberto Burri realizzata sulle macerie della vecchia Gibellina distrutta dal terremoto del Belice del 1968.",
    description: "",
    whyVisit: "È insieme memoriale, land art e mappa astratta della città perduta, con una scala difficilmente percepibile dalle fotografie.",
    whatToSee: "Cammina tra le fenditure del cemento e osserva come i blocchi ricalcano il tessuto dell'antico abitato.",
    practicalTips: "Il sito è molto esposto: porta acqua e protezione dal sole e lascia tempo per percorrerlo a piedi, non solo guardarlo dal belvedere.",
    sourceLabel: "Fondazione Burri - Grande Cretto",
    sourceUrl: "https://fondazioneburri.org/grandi-opere/grande-cretto-gibellina/",
  },
  "saline-dello-stagnone": {
    shortIntro: "Paesaggio di vasche salanti, mulini e acque basse nella laguna dello Stagnone di Marsala.",
    description: "",
    whyVisit: "Unisce attività produttiva tradizionale, paesaggio culturale e uno dei tramonti più caratteristici della costa occidentale.",
    whatToSee: "Guarda geometrie delle vasche, cumuli di sale, mulini e isole della laguna sullo sfondo.",
    practicalTips: "Se possibile resta verso il tramonto, ma verifica in anticipo accessi, visite ai mulini e condizioni del vento.",
    sourceLabel: "Comune di Marsala - Saline",
    sourceUrl: "https://www.comune.marsala.tp.it/it/vivere/saline-di-marsala",
  },
  "arrival-trapani": {
    shortIntro: "Tappa operativa di arrivo a Trapani dopo Gibellina e lo Stagnone.",
    description: "",
    whyVisit: "Segna l'ingresso nel tratto occidentale del viaggio, da cui partiranno centro storico, Egadi e costa di San Vito.",
    whatToSee: "All'arrivo orientati rispetto al porto e al centro storico prima di parcheggiare definitivamente.",
    practicalTips: "Non aggiungere visite obbligatorie se la giornata è stata lunga: Trapani avrà una giornata dedicata.",
    sourceLabel: "Visit Sicily - Trapani",
    sourceUrl: "https://www.visitsicily.info/localita/trapani/",
  },
  "porta-oscura-torre-dellorologio": {
    shortIntro: "Porta Oscura e la Torre dell'Orologio segnano uno degli accessi storici al centro di Trapani; la torre ospita un antico orologio astronomico.",
    description: "",
    whyVisit: "È un punto identitario della città e introduce bene la passeggiata nel nucleo storico.",
    whatToSee: "Guarda quadranti, meccanismi visibili dall'esterno, arco e raccordo con le strade del centro.",
    practicalTips: "Fermati qualche minuto e poi prosegui a piedi: è una tappa naturalmente integrata nel percorso.",
    sourceLabel: "Visit Sicily - Trapani",
    sourceUrl: "https://www.visitsicily.info/localita/trapani/",
  },
  "cattedrale-san-lorenzo": {
    shortIntro: "Cattedrale di Trapani lungo Corso Vittorio Emanuele, dall'aspetto barocco maturato attraverso ricostruzioni e ampliamenti.",
    description: "",
    whyVisit: "È il principale edificio religioso del centro e si inserisce direttamente nella passeggiata storica.",
    whatToSee: "Osserva facciata, cupola e l'interno se accessibile, confrontandoli con gli edifici civili del corso.",
    practicalTips: "Visitala fuori dalle celebrazioni e mantieni una sosta breve se la giornata comprende già molte tappe.",
    sourceLabel: "Visit Sicily - Trapani",
    sourceUrl: "https://www.visitsicily.info/localita/trapani/",
  },
  "corso-vittorio-emanuele": {
    shortIntro: "Asse pedonale del centro storico di Trapani, fiancheggiato da chiese, palazzi e caffè.",
    description: "",
    whyVisit: "È il modo più semplice per percepire la forma allungata della città storica tra porto e mare.",
    whatToSee: "Guarda facciate, balconi e cambi di prospettiva verso le strade trasversali.",
    practicalTips: "Percorrilo lentamente e usalo come collegamento tra le tappe, evitando di trasformarlo in un semplice trasferimento.",
    sourceLabel: "Visit Sicily - Trapani",
    sourceUrl: "https://www.visitsicily.info/localita/trapani/",
  },
  "piazza-ex-mercato-del-pesce": {
    shortIntro: "Spazio urbano semicircolare vicino al mare, nato come sede del mercato del pesce e oggi riconoscibile per il colonnato.",
    description: "",
    whyVisit: "Racconta il rapporto storico di Trapani con pesca e commercio marittimo.",
    whatToSee: "Guarda il colonnato, la fontana centrale e l'apertura verso il lungomare.",
    practicalTips: "È una sosta breve: abbinala alle Mura di Tramontana e alla passeggiata sul mare.",
    sourceLabel: "Visit Sicily - Trapani",
    sourceUrl: "https://www.visitsicily.info/localita/trapani/",
  },
  "mura-di-tramontana": {
    shortIntro: "Passeggiata lungo il fronte settentrionale delle antiche mura di Trapani, direttamente affacciata sul mare.",
    description: "",
    whyVisit: "È uno dei punti migliori per percepire la città come penisola stretta tra due mari.",
    whatToSee: "Guarda bastioni, spiaggia sottostante, profilo del centro e luce sul Tirreno.",
    practicalTips: "Tienila per il tardo pomeriggio o per una giornata ventilata ma non troppo agitata.",
    sourceLabel: "Visit Sicily - Trapani",
    sourceUrl: "https://www.visitsicily.info/localita/trapani/",
  },
  "boat-tour-favignana": {
    shortIntro: "Escursione in barca attorno a Favignana, la maggiore delle Egadi, famosa per cale, fondali chiari e costa calcarea.",
    description: "",
    whyVisit: "Dal mare si colgono meglio la varietà delle insenature e il rapporto dell'isola con la tradizione marinara.",
    whatToSee: "Osserva colore dell'acqua, cave costiere, faraglioni e differenze tra le varie cale.",
    practicalTips: "Programma la giornata sul meteo marino reale: vento e stato del mare possono cambiare rotta e soste.",
    sourceLabel: "Visit Sicily - Isole Egadi",
    sourceUrl: "https://www.visitsicily.info/egadi-favignana-levanzo-marettimo/",
  },
  "calette-santa-margherita": {
    shortIntro: "Tratto di costa nell'area di San Vito Lo Capo scelto per una sosta balneare più raccolta rispetto alla spiaggia principale.",
    description: "",
    whyVisit: "Serve a vivere la costa occidentale con un ritmo più lento dopo la giornata in barca.",
    whatToSee: "Guarda trasparenza dell'acqua, fondale e profilo roccioso della costa.",
    practicalTips: "Porta scarpe da scoglio e non dare per scontati servizi o ombra: le calette possono essere molto essenziali.",
    sourceLabel: "Visit Sicily - Sicilia occidentale",
    sourceUrl: "https://www.visitsicily.info/itinerario/scopello-san-vito-lo-capo-marsala-dintorni/",
  },
  "san-vito-lo-capo": {
    shortIntro: "Borgo costiero raccolto attorno alla grande spiaggia chiara, con il Monte Monaco a dominare il paesaggio.",
    description: "",
    whyVisit: "È una delle soste balneari più famose della Sicilia occidentale e una base ideale tra Zingaro, Scopello ed Egadi.",
    whatToSee: "Guarda il contrasto tra spiaggia, mare turchese e montagna, oltre al Santuario nel centro del paese.",
    practicalTips: "Alterna mare e passeggiata; nelle ore più calde cerca ombra e verifica sempre vento e condizioni del mare.",
    sourceLabel: "Visit Sicily - Sicilia occidentale",
    sourceUrl: "https://www.visitsicily.info/itinerario/scopello-san-vito-lo-capo-marsala-dintorni/",
  },
  "cala-bianca": {
    shortIntro: "Piccola cala rocciosa nella costa di Scopello, apprezzata per acqua trasparente e ambiente poco urbanizzato.",
    description: "",
    whyVisit: "È una sosta più naturale rispetto alle spiagge attrezzate e prepara bene alla Tonnara e allo Zingaro.",
    whatToSee: "Guarda i fondali, le rocce chiare e la macchia mediterranea che scende verso il mare.",
    practicalTips: "Accesso e parcheggio possono essere scomodi: usa scarpe adatte e non contare su servizi in spiaggia.",
    sourceLabel: "Visit Sicily - Sicilia occidentale",
    sourceUrl: "https://www.visitsicily.info/itinerario/scopello-san-vito-lo-capo-marsala-dintorni/",
  },
  "tonnara-di-scopello": {
    shortIntro: "Antico complesso della pesca del tonno affacciato su una baia dominata dai faraglioni di Scopello.",
    description: "",
    whyVisit: "È uno dei paesaggi costieri più iconici della Sicilia occidentale perché unisce archeologia industriale e mare.",
    whatToSee: "Guarda edifici della tonnara, torri, faraglioni e il rapporto tra strutture di lavoro e piccola baia.",
    practicalTips: "L'accesso è regolato e può richiedere prenotazione o biglietto: verifica le modalità aggiornate prima di arrivare.",
    sourceLabel: "Visit Sicily - Sicilia occidentale",
    sourceUrl: "https://www.visitsicily.info/itinerario/scopello-san-vito-lo-capo-marsala-dintorni/",
  },
  "riserva-dello-zingaro": {
    shortIntro: "Riserva costiera tra Scopello e San Vito Lo Capo, con circa sette chilometri di costa, sentieri, calette e macchia mediterranea.",
    description: "",
    whyVisit: "È una delle giornate naturalistiche più complete del viaggio: il paesaggio si scopre camminando, non da un singolo belvedere.",
    whatToSee: "Osserva palme nane, falesie, calette e cambiamenti della vegetazione lungo il sentiero costiero.",
    practicalTips: "Controlla aperture e prescrizioni ufficiali, porta molta acqua e scarpe da trekking: nella riserva non va improvvisata l'attrezzatura.",
    sourceLabel: "Riserva Naturale Orientata dello Zingaro",
    sourceUrl: "https://www.riservazingaro.it/",
  },
  "palazzo-della-zisa": {
    shortIntro: "Palazzo reale normanno del XII secolo, progettato come residenza di delizie e oggi parte del sito UNESCO arabo-normanno.",
    description: "",
    whyVisit: "È uno dei luoghi migliori per leggere l'incontro tra cultura islamica e committenza normanna nella Palermo medievale.",
    whatToSee: "Guarda la Sala della Fontana, le geometrie decorative, il sistema d'acqua e ventilazione e la severa massa esterna.",
    practicalTips: "L'interno è importante quanto l'esterno: verifica biglietti e orari prima della giornata palermitana.",
    sourceLabel: "Comune di Palermo - Palazzo della Zisa",
    sourceUrl: "https://turismo.comune.palermo.it/palermo-welcome-luogo-dettaglio.php?det=17&id=71&tp=68",
  },
  "palazzo-della-cuba": {
    shortIntro: "Padiglione reale costruito nel 1180 per Guglielmo II all'interno del parco normanno del Genoardo.",
    description: "",
    whyVisit: "Completa la lettura della Palermo arabo-normanna mostrando l'architettura di svago della corte fuori dal nucleo religioso.",
    whatToSee: "Osserva forma compatta, arcate ogivali, spesse murature e i resti della fontana interna che contribuiva a rinfrescare gli ambienti.",
    practicalTips: "Abbinala alla Zisa: viste insieme raccontano meglio il paesaggio reale normanno.",
    sourceLabel: "Comune di Palermo - Cuba",
    sourceUrl: "https://turismo.comune.palermo.it/palermo-welcome-luogo-dettaglio.php?det=17&id=74&tp=68",
  },
  "camera-delle-meraviglie": {
    shortIntro: "Ambiente privato palermitano emerso durante lavori di restauro, caratterizzato da pareti blu con iscrizioni e decorazioni di gusto orientalista.",
    description: "",
    whyVisit: "È una tappa insolita che aggiunge un piccolo enigma alla storia multiculturale della città.",
    whatToSee: "Guarda la ripetizione dei motivi calligrafici, il colore delle pareti e l'effetto immersivo dell'ambiente.",
    practicalTips: "Essendo uno spazio particolare e non un museo tradizionale, verifica sempre modalità di visita e prenotazione.",
    sourceLabel: "Comune di Palermo - Turismo",
    sourceUrl: "https://turismo.comune.palermo.it/",
  },
  "santa-maria-dello-spasimo": {
    shortIntro: "Chiesa tardo-gotica della Kalsa iniziata nel 1506 e rimasta incompleta, oggi celebre soprattutto per la navata centrale a cielo aperto.",
    description: "",
    whyVisit: "Il suo fascino nasce proprio dall'incompiutezza e dalle molte vite avute nei secoli, da spazio religioso a luogo culturale.",
    whatToSee: "Guarda archi ogivali, cappelle laterali, murature senza copertura e il cielo incorniciato dalla navata.",
    practicalTips: "Verifica l'accesso perché eventi e attività culturali possono modificare la fruizione.",
    sourceLabel: "Comune di Palermo - Spasimo",
    sourceUrl: "https://turismo.comune.palermo.it/palermo-welcome-luogo-dettaglio.php?id=276&tp=68",
  },
  "murale-falcone-e-borsellino": {
    shortIntro: "Tappa di memoria civile legata alle opere urbane dedicate a Giovanni Falcone e Paolo Borsellino e alla lotta contro Cosa nostra.",
    description: "",
    whyVisit: "Porta nel viaggio un pezzo di storia contemporanea di Palermo, lontano dalla sola dimensione monumentale.",
    whatToSee: "Osserva la scala dei ritratti, il rapporto con gli edifici e il contesto urbano vicino all'Ucciardone.",
    practicalTips: "È un luogo di memoria: meglio una sosta breve e consapevole che una semplice foto.",
    sourceLabel: "Fondazione Falcone - Spazi Capaci",
    sourceUrl: "https://www.fondazionefalcone.org/fatti/23maggio-dai-luoghi-simbolo-della-lotta-alla-mafia-nasce-spazi-capaci-progetto-di-memoria-4-0-riprendiamoci-le-citta-attraverso-larte/",
  },
  "porta-felice": {
    shortIntro: "Porta monumentale sul fronte mare di Palermo, iniziata alla fine del Cinquecento e completata nel Seicento come ingresso orientale del Cassaro.",
    description: "",
    whyVisit: "Segna fisicamente il passaggio tra il centro storico e il Foro Italico.",
    whatToSee: "Guarda i due piloni separati, le differenze tra fronte verso il mare e fronte urbano, marmi, nicchie e stemmi.",
    practicalTips: "Passaci a piedi collegando Via Vittorio Emanuele alla Cala o al Foro Italico.",
    sourceLabel: "Comune di Palermo - Porta Felice",
    sourceUrl: "https://turismo.comune.palermo.it/palermo-welcome-luogo-dettaglio.php?det=17&id=283&tp=68",
  },
  "via-cala": {
    shortIntro: "Passeggiata lungo l'antico porto della Cala, oggi spazio urbano sul waterfront tra barche, mura e centro storico.",
    description: "",
    whyVisit: "Mostra il rapporto diretto di Palermo con il mare, spesso meno evidente camminando dentro i quartieri centrali.",
    whatToSee: "Guarda il porto curvo, il profilo della città, le barche e le connessioni verso Kalsa e Vucciria.",
    practicalTips: "È ideale come tratto di decompressione tra monumenti: meglio con luce del tardo pomeriggio.",
    sourceLabel: "Comune di Palermo - Turismo",
    sourceUrl: "https://turismo.comune.palermo.it/",
  },
  "la-vucciria": {
    shortIntro: "Storico quartiere-mercato di Palermo, oggi mescola bancarelle residue, street food, locali e una vita serale molto intensa.",
    description: "",
    whyVisit: "È uno dei luoghi dove il carattere popolare della città si percepisce più direttamente.",
    whatToSee: "Guarda vicoli, insegne, banchi, piazze e tracce del mercato tradizionale, non solo i locali più recenti.",
    practicalTips: "Passa con attenzione agli effetti personali nelle ore affollate e scegli cibo da attività con buona rotazione e pulizia visibile.",
    sourceLabel: "Visit Sicily - Palermo",
    sourceUrl: "https://www.visitsicily.info/localita/palermo/",
  },
  "teatro-politeama-garibaldi": {
    shortIntro: "Grande teatro ottocentesco di Piazza Ruggero Settimo, riconoscibile per la facciata ad arco monumentale e la quadriga sommitale.",
    description: "",
    whyVisit: "Introduce la Palermo borghese dell'Ottocento e crea un forte contrasto con i quartieri storici visitati poco prima.",
    whatToSee: "Guarda l'arco d'ingresso, il colonnato, la quadriga e l'ampiezza della piazza circostante.",
    practicalTips: "Se non hai tempo per l'interno, la lettura esterna è già efficace; di sera l'illuminazione valorizza il complesso.",
    sourceLabel: "Comune di Palermo - Turismo",
    sourceUrl: "https://turismo.comune.palermo.it/",
  },
  "cefalu-flexible-return-day": {
    shortIntro: "Cefalù è un borgo costiero dominato dalla Cattedrale normanna e dalla Rocca, parte del sito UNESCO arabo-normanno insieme a Palermo e Monreale.",
    description: "",
    whyVisit: "È una giornata flessibile ideale per chiudere il viaggio combinando patrimonio, vicoli medievali e mare.",
    whatToSee: "Se il tempo lo permette, concentra la visita su Cattedrale e piazza, lavatoio medievale, porto vecchio e scorci sotto la Rocca.",
    practicalTips: "Non riempire troppo l'ultima giornata: scegli tra centro storico, mare e Rocca in base a orario di rientro e caldo.",
    sourceLabel: "UNESCO - Arab-Norman Palermo and Cefalù",
    sourceUrl: "https://whc.unesco.org/en/list/1487/",
  },
  "antica-dolceria-bonajuto": {
    shortIntro: "Dolceria storica di Modica, attiva da oltre un secolo e legata alla lavorazione tradizionale del cioccolato modicano.",
    description: "",
    whyVisit: "È una tappa quasi didattica: permette di collegare il gusto alla storia produttiva della città.",
    whatToSee: "Assaggia il cioccolato dalla consistenza granulosa e confronta percentuali e aromatizzazioni senza coprire tutto con troppi gusti.",
    practicalTips: "Meglio pochi assaggi mirati; verifica sul sito eventuali visite o esperienze disponibili.",
    sourceLabel: "Antica Dolceria Bonajuto - sito ufficiale",
    sourceUrl: "https://www.bonajuto.it/",
  },
  "bam-bar": {
    shortIntro: "Bar molto conosciuto a Taormina per granita siciliana e brioche, in posizione comoda rispetto al centro.",
    description: "",
    whyVisit: "È una pausa coerente con la tradizione locale e spezza bene la parte monumentale della mattina.",
    whatToSee: "Qui 'da guardare' significa soprattutto scegliere gusti stagionali e osservare consistenza e servizio della granita con brioche.",
    practicalTips: "Può esserci attesa nei periodi affollati: usalo come sosta flessibile, non come appuntamento con tempi strettissimi.",
    sourceLabel: "Bam Bar - pagina ufficiale Facebook",
    sourceUrl: "https://www.facebook.com/BamBar-Taormina-291496720867523/",
  },
  "caffe-sicilia": {
    shortIntro: "Storico caffè-pasticceria di Noto attivo dal 1892, noto per una ricerca contemporanea sui sapori e sulle materie prime siciliane.",
    description: "",
    whyVisit: "È una delle soste gastronomiche più interessanti del percorso barocco di Noto e si trova direttamente sul corso.",
    whatToSee: "Prova una preparazione che valorizzi agrumi, mandorla o granita invece di ordinare molti dolci diversi.",
    practicalTips: "Se trovi coda, tienila flessibile: il centro di Noto consente di ripassare davanti al locale più tardi.",
    sourceLabel: "Caffè Sicilia - sito ufficiale",
    sourceUrl: "https://www.caffesicilia.it/",
  },
  "castello-maniace": {
    shortIntro: "Fortezza federiciana del XIII secolo posta sulla punta meridionale di Ortigia, in posizione dominante sul porto e sul mare.",
    description: "",
    whyVisit: "Chiude fisicamente l'isola e permette di leggere il ruolo strategico di Siracusa oltre la dimensione barocca.",
    whatToSee: "Guarda il portale, le massicce strutture difensive, la grande sala e le viste sulle due sponde di Ortigia.",
    practicalTips: "Verifica orari e accesso prima di arrivare: è fuori dall'asse più diretto del centro e richiede tempo dedicato.",
    sourceLabel: "Visit Sicily - Ortigia",
    sourceUrl: "https://www.visitsicily.info/attrazione/isola-di-ortigia/",
  },
  "cretto-di-burri-belvedere": {
    shortIntro: "Punto di osservazione sul Grande Cretto di Alberto Burri, l'opera ambientale che ricopre le macerie della vecchia Gibellina.",
    description: "",
    whyVisit: "Dal belvedere si coglie meglio la scala complessiva dell'opera prima o dopo aver camminato tra le fenditure.",
    whatToSee: "Guarda il disegno bianco che ricostruisce la trama dell'abitato e il contrasto con il paesaggio del Belice.",
    practicalTips: "Se hai tempo, non fermarti solo al punto panoramico: la percezione cambia completamente entrando nei percorsi dell'opera.",
    sourceLabel: "Fondazione Burri - Grande Cretto",
    sourceUrl: "https://fondazioneburri.org/grandi-opere/grande-cretto-gibellina/",
  },
  "la-bettolaccia": {
    shortIntro: "Ristorante del centro di Trapani con cucina legata alla tradizione siciliana e particolare attenzione al pesce.",
    description: "",
    whyVisit: "È una scelta adatta per provare cucina locale in una giornata dedicata alla città e al mare.",
    whatToSee: "Cerca piatti basati sul pescato e sulle ricette trapanesi piuttosto che un menu troppo generico.",
    practicalTips: "Prenota se vuoi andarci a un orario preciso e chiedi sempre disponibilità reale del pescato.",
    sourceLabel: "Touring Club Italiano - La Bettolaccia",
    sourceUrl: "https://www.touringclub.it/destinazioni/trapani/mangiare/325607-la-bettolaccia",
  },
  "la-sirenetta-gelateria-artigianale": {
    shortIntro: "Gelateria artigianale di San Vito Lo Capo, adatta a una pausa dopo spiaggia o passeggiata nel borgo.",
    description: "",
    whyVisit: "È un modo leggero per inserire un assaggio locale senza trasformare la giornata di mare in un itinerario gastronomico troppo rigido.",
    whatToSee: "Guarda i gusti disponibili quel giorno e privilegia quelli stagionali o legati a frutta e ingredienti siciliani.",
    practicalTips: "Passa quando rientri dal mare e verifica sede/orari sulla pagina ufficiale.",
    sourceLabel: "Gelateria La Sirenetta - sito ufficiale",
    sourceUrl: "https://www.gelaterialasirenetta.it/it/contatti",
  },
  "museo-civico-castello-ursino": {
    shortIntro: "Castello fatto costruire da Federico II nel XIII secolo e oggi sede del Museo Civico di Catania.",
    description: "",
    whyVisit: "È una delle rare grandi testimonianze medievali della città e conserva collezioni che ampliano la visita oltre il barocco.",
    whatToSee: "Guarda la struttura quadrangolare, le torri cilindriche e, all'interno, le raccolte archeologiche e storico-artistiche.",
    practicalTips: "È una vera visita museale: se la aggiungi al giorno 1, considera almeno un'ora e verifica orari ufficiali.",
    sourceLabel: "Museo Civico Castello Ursino - Comune di Catania",
    sourceUrl: "https://museocivicocastelloursino.comune.catania.it/",
  },
  "museo-del-sale-saline-dello-stagnone": {
    shortIntro: "Visita dedicata alla cultura del sale e ai mulini delle saline dello Stagnone, dove il paesaggio è ancora legato a un processo produttivo tradizionale.",
    description: "",
    whyVisit: "Aiuta a capire cosa stai guardando nelle vasche: non solo panorama, ma un sistema di raccolta e gestione dell'acqua salata.",
    whatToSee: "Guarda mulino, attrezzi, vasche e passaggi del ciclo del sale, collegandoli al paesaggio esterno.",
    practicalTips: "Abbinalo alle saline e al tramonto; verifica visite guidate e accessi direttamente con il gestore.",
    sourceLabel: "Saline Ettore e Infersa - Il Mulino",
    sourceUrl: "https://www.seisaline.it/il-mulino/",
  },
  "nivera-il-gelato-di-natura": {
    shortIntro: "Gelateria artigianale di Scicli orientata alla lavorazione del gelato con forte attenzione agli ingredienti.",
    description: "",
    whyVisit: "È una pausa semplice da inserire dopo la visita del centro barocco e completa il lato gastronomico della giornata iblea.",
    whatToSee: "Scegli uno o due gusti e valuta soprattutto consistenza e intensità delle materie prime.",
    practicalTips: "Controlla gusti e apertura del giorno; dopo una giornata lunga è meglio una sosta breve che aggiungere un'altra visita.",
    sourceLabel: "NIVERA - sito ufficiale",
    sourceUrl: "https://www.nivera-gelateria.com/",
  },
  "pasticceria-savia": {
    shortIntro: "Storica pasticceria catanese nata alla fine dell'Ottocento lungo Via Etnea, legata alla tradizione dolce e salata siciliana.",
    description: "",
    whyVisit: "È una sosta gastronomica classica per provare specialità locali senza allontanarsi dall'itinerario del centro.",
    whatToSee: "Più che 'guardare', qui vale assaggiare: cannolo, cassata o un pezzo di rosticceria secondo fame e orario.",
    practicalTips: "Evita di ordinare troppo se hai altre soste food nella giornata; verifica sempre sede e orari ufficiali.",
    sourceLabel: "Pasticceria Savia - storia",
    sourceUrl: "https://lnx.savia.it/content/8-la-storia",
  },
  "pasticceria-spalti-di-sansica-benvenuto": {
    shortIntro: "Pasticceria trapanese tradizionale indicata per una pausa dolce o per provare prodotti di rosticceria locale.",
    description: "",
    whyVisit: "È una tappa food pratica lungo il soggiorno a Trapani e permette di alternare ristoranti e street food.",
    whatToSee: "Valuta cannoli, prodotti da forno e specialità disponibili al banco invece di puntare su un solo prodotto prefissato.",
    practicalTips: "La documentazione ufficiale online è limitata: controlla sul posto disponibilità e orari prima di deviare dal percorso.",
    sourceLabel: "Scheda attività - DovePasticcio",
    sourceUrl: "https://www.dovepasticcio.it/pasticcerie/dettaglio/5724/pasticceria-spalti-di-sansica-benvenuto-and-c-s-n-c-a-trapani",
  },
  "ristorante-antichi-sapori": {
    shortIntro: "Ristorante trapanese nato nei primi anni Duemila e orientato alla cucina tradizionale locale, soprattutto di mare.",
    description: "",
    whyVisit: "È una buona occasione per provare ricette trapanesi in un contesto meno veloce rispetto allo street food.",
    whatToSee: "Cerca nel menu piatti di pesce e preparazioni legate alla tradizione della costa occidentale.",
    practicalTips: "Prenota e chiedi i piatti realmente disponibili quel giorno: la materia prima fresca conta più del menu letto online.",
    sourceLabel: "Ristorante Antichi Sapori - sito ufficiale",
    sourceUrl: "https://www.antichisaporitrapani.it/",
  },
  "ristorante-timeo": {
    shortIntro: "Ristorante del Grand Hotel Timeo a Taormina, con cucina ispirata alla Sicilia e terrazze panoramiche verso Etna e baia di Naxos.",
    description: "",
    whyVisit: "È una scelta più raffinata, utile soprattutto se vuoi trasformare il pasto in parte dell'esperienza panoramica.",
    whatToSee: "Oltre ai piatti, il punto forte è la vista: chiedi se possibile un tavolo in posizione panoramica.",
    practicalTips: "Prenota e controlla dress code, menu e disponibilità sul sito ufficiale; non considerarlo una sosta food rapida.",
    sourceLabel: "Belmond Grand Hotel Timeo - Dining",
    sourceUrl: "https://www.belmond.com/it/hotels/europe/italy/taormina/belmond-grand-hotel-timeo/dining",
  },
};
